include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: true
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_print: true
    one_member_abstracts: true
    prefer_const_constructors: true
    use_setters_to_change_properties: false
    non_constant_identifier_names: false
    file_names: false
    omit_local_variable_types: false
    constant_identifier_names: false
    avoid_positional_boolean_parameters: false
    avoid_function_literals_in_foreach_calls: false
    avoid_catches_without_on_clauses: false
    avoid_classes_with_only_static_members: false
    unnecessary_lambdas: false
    prefer_final_fields: false